version: "3"

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt

  nginx:
    depends_on:
      - certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

volumes:
  certbot_www: {}
  certbot_conf: {}
